# Generated by Django 5.1.4 on 2024-12-14 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Autor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        help_text="Input name autor",
                        max_length=100,
                        verbose_name="Name autor",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        help_text="Input lastname autor",
                        max_length=100,
                        verbose_name="Lastname autor",
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True,
                        help_text="Input date of birth",
                        null=True,
                        verbose_name="Date of birth",
                    ),
                ),
                (
                    "about",
                    models.TextField(
                        help_text="Input info about autor", verbose_name="About autor"
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        help_text="Input foto autor",
                        null=True,
                        upload_to="images",
                        verbose_name="Foto autor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Input genre book",
                        max_length=200,
                        verbose_name="Genre book",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Input language book",
                        max_length=20,
                        verbose_name="Language book",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Publisher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Input name of publisher",
                        max_length=20,
                        verbose_name="Publisher",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Status",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Input status exemplar of book",
                        max_length=20,
                        verbose_name="STATUS",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Input name book",
                        max_length=200,
                        verbose_name="Name book",
                    ),
                ),
                (
                    "year",
                    models.CharField(help_text="Choice year publish", max_length=4),
                ),
                (
                    "summary",
                    models.TextField(
                        help_text="Input summary of book",
                        max_length=1000,
                        verbose_name="Annotation of book",
                    ),
                ),
                (
                    "ibsn",
                    models.CharField(
                        help_text="Must input 13 char",
                        max_length=13,
                        verbose_name="IBSN book",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Input price of book",
                        max_digits=7,
                        verbose_name="Price (usd.)",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        help_text="Input image book",
                        upload_to="images",
                        verbose_name="Image book",
                    ),
                ),
                (
                    "author",
                    models.ManyToManyField(
                        help_text="Choice author(s) book",
                        to="catalog.autor",
                        verbose_name="Autor(s) book",
                    ),
                ),
                (
                    "genre",
                    models.ForeignKey(
                        help_text="Choice genre for book",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.genre",
                        verbose_name="Genre book",
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        help_text="Choice language for book",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.language",
                        verbose_name="Language book",
                    ),
                ),
                (
                    "publisher",
                    models.ForeignKey(
                        help_text="Choice publisher",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.publisher",
                        verbose_name="Publisher",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BookInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "inv_nom",
                    models.CharField(
                        help_text="Input inventar number exemplar",
                        max_length=20,
                        null=True,
                        verbose_name="Inventar number",
                    ),
                ),
                (
                    "due_back",
                    models.DateField(
                        blank=True,
                        help_text="Input end time status",
                        null=True,
                        verbose_name="Date of end status",
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.book",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        help_text="Change state exemplar",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.status",
                        verbose_name="Status exemplar book",
                    ),
                ),
            ],
            options={
                "ordering": ["due_back"],
            },
        ),
    ]
